name: TheWarpPlugin
version: '2.1.0'
main: com.coffee.warpCommand.Main
api-version: '1.21'
authors: [Coffee]
description: Plugin for testing
commands:
  warp:
    description: Salve localizações e volte rapidamente a elas!
    usage: /warp <list | rename | remove | set | to> [name]
