name: TheWarpPlugin
version: '1.1.0' #This NEEDS to match the GitHub version.
main: com.coffee.warpCommand.Main
api-version: '1.21'
authors: [Coffee1307]
description: Plugin for all your warping needs!
commands:
  warp:
    description: Save locations and quickly return to them!
    usage: /warp <list | rename | remove | set | to> [name]
  warpconfig:
    description: Toggle auto-update checks
    usage: /warpconfig <enable|disable>
  config: