name: TheWarpPlugin
version: '1.1.0'
main: com.coffee.WarpPlugin.Main
api-version: '1.21'
authors: [Coffee1307]
description: Advanced warp system with public/private locations

permissions:
  warp.public:
    description: "Access public warps"
    default: true
  warp.private:
    description: "Manage private warps"
    default: true
  warp.admin:
    description: "Manage all warps"
    default: op

commands:
  warp:
    description: Teleport to locations
    usage: /warp <list | set | remove | rename | to> [name] [public]
  warpconfig:
    description: Configure warp settings
    usage: /warpconfig <WarpOpOnly | WarpPublicOnly> <enable | disable>
    permission: warp.admin
    permission-message: "§cYou need to be OP to use this command!"